config/routes.rb
Sence::Application.routes.draw do
  
  resources :category_questions

  resources :categories

  resources :profiles

  resources :answers do
    collection do
      get 'history' => 'answers#history'
      get 'summary' => 'answers#summary'
    end
  end

  resources :questions do 
    collection do
      get 'mine' => 'questions#index'
      get 'nopicture' => 'questions#index'
      get 'random'
      get 'wapproval' => 'questions#index'
      get 'wimages'
    end
    member do
      post :approve
      get 'stats'
    end
  end
  
  devise_for :users,:controllers => {:sessions => "sessions",:registrations => "registrations"}
  
  resources :users do
    resources :questions
    resources :answers
    resources :profiles
  end

  match 'logout' => 'devise/session#destroy'
  match 'myrank' => 'profiles#myrank'
  match 'most' => 'statistics#most_answered'
  match 'gap' => 'statistics#gap'
  match 'aomq' => 'statistics#aomq'
  

   root :to => 'home#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  
  has_many :category_questions
  has_many :categories, :through => :category_questions
 
  accepts_nested_attributes_for :category_questions, :allow_destroy => true
  
  @@points_for_create=10
  
  def points_for_create
    @@points_for_create
  end
  
  #before_save :capitalize_fields
  before_create :randomize_file_name
  #TODO: soru update ederken filename randomize edilmiyor. before_update eklendiğinde ise sadece text
  #edit ediliginde veya tek 1 resim edildiğinde her 2 filename randomize ediliyor. diğer resim kayboluyor.
  #before_update :randomize_file_name
  
  has_attached_file :opt1_image, 
                    :styles => { :medium => "180x180>", :thumb => "32x32>" },
                    :default_url => '/assets/missing.png',
                    :url=>"/system/:class_images/:basename_:style.:extension"
  has_attached_file :opt2_image, 
                    :styles => { :medium => "180x180>", :thumb => "32x32>" },
                    :default_url => '/assets/missing.png',
                    :url=>"/system/:class_images/:basename_:style.:extension"
  
  STATUSES = %w(wapproval approved deleted)
  
  #validates_uniqueness_of :opt1, :scope => [:opt2]
  validates_presence_of :status , :opt1, :opt2
  validates_inclusion_of :status, :in => STATUSES
  
  def randomize_file_name
    if !opt1_image_file_name.blank?
      extension = File.extname(opt1_image_file_name).downcase
      self.opt1_image.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
    end
    
    if !opt2_image_file_name.blank?
      extension = File.extname(opt2_image_file_name).downcase
      self.opt2_image.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
    end
  end
  
  def user_email
    self.user.email if !self.user.nil?
  end
  
  scope :nopicture, where('opt1_image_file_name is null or opt2_image_file_name is null')
  scope :active, where("status='approved'")
  scope :fresh, lambda { |user| where('id not in (select distinct question_id from answers where user_id= ?)',user.id) }
  scope :pictured, where('opt1_image_file_name is not null and opt2_image_file_name is not null')
  
  def capitalize_fields
    self.opt1=UnicodeUtils.titlecase(self.opt1)
    self.opt2=UnicodeUtils.titlecase(self.opt2)
  end
  
  
  class << self 
    STATUSES.each do |status_name|
      define_method "all_#{status_name}" do
        where(:status => status_name)
      end 
    end
  end
  
  # Status Accessors
  STATUSES.each do |status_name| 
    define_method "#{status_name}?" do
      status == status_name 
    end
  end
  
  def approve
    self.update_attribute(:status,STATUSES[1])
  end
  
  
  attr_accessor :opt1_image_client
  attr_accessor :opt2_image_client

  before_validation :decode_images
  
  def decode_images
    if !self.opt1_image_client.nil? and !self.opt1_image_client.empty?
      data = StringIO.new(Base64.decode64(self.opt1_image_client))
      data.class.class_eval { attr_accessor :original_filename, :content_type }
      data.original_filename = "cover1.jpg"
      data.content_type = "image/jpeg"
      self.opt1_image = data
    end
    
    if !self.opt2_image_client.nil? and !self.opt2_image_client.empty?
      data = StringIO.new(Base64.decode64(self.opt2_image_client))
      data.class.class_eval { attr_accessor :original_filename, :content_type }
      data.original_filename = "cover.jpg"
      data.content_type = "image/jpeg"
      self.opt2_image = data
    end
  end
end

app/controllers/questions_controller.rb
require 'fileutils'
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  load_and_authorize_resource
  skip_authorize_resource :only => :random
  
  def index
    if current_uri.include?('mine')
      @user=User.find(current_user)
      @questions = @user.questions
      @@page_back="mine"
    elsif current_uri.include?('nopicture')
      @questions = Question.nopicture
      @@page_back="nopicture"
    elsif current_uri.include?('wapproval')
      @@page_back="wapproval"
      @questions = Question.all_wapproval
    elsif params[:user_id]
      @user=User.find(params[:user_id])
      @questions = @user.questions
    else
      @questions = Question.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end
  
  def stats
    @question=Question.find(params[:id])
    
    respond_to do |format|
      format.json{render json:@question.to_json(:only=>[:opt1_ac,:opt2_ac])}
    end
    
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new
    @question.category_questions.build
    @categories= Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
    @categories= Category.all
  end

  # POST /questions
  # POST /questions.json
  def create
    @user = User.find(current_user)
    @question = Question.new(params[:question])
    profile=@user.profile
    profile.points=(@user.profile.points).to_i+(@question.points_for_create)
    @question.user_id=@user.id
   
    respond_to do |format|
      ActiveRecord::Base.transaction do
        @question.save!
        profile.save!
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json:{:id=>@question.id,:points_gained=>@question.points_for_create,:points=>profile.points}, status: :created, location: @question }
      end      
    end
    
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved
      format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
        
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      if @@page_back=='wapproval'
        format.html { redirect_to wapproval_questions_url }
      elsif @@page_back=="nopicture"
        format.html { redirect_to nopicture_questions_url }
      elsif @@page_back=="mine"
        format.html { redirect_to mine_questions_url }
      else
        format.html { redirect_to questions_url }
      end
      
      format.json { head :no_content }
    end
  end
  
  def random
     if params[:auth_token]
       reset_session
     end
  
    @user = User.find(current_user)
    @question = Question.fresh(@user).active.pictured.random
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question.to_json(:only=>[:id,:opt1,:opt1_image_file_name,:opt2,:opt2_image_file_name,:point]) }
    end
  end
  
  def image_migrate
    
    questions=Question.pictured
    strnotice="not migrated"
    
    questions.each do |question|
      begin
        filename=SecureRandom.hex(16)
        qid=question.id.to_s
        
        from_path=Rails.root.to_s+'/public/system/opt1_images/'+qid+'/original/'+question.opt1_image_file_name
        to_path=Rails.root.to_s+'/public/system/questions_images/'+filename+'_original.jpg'
        FileUtils.cp(from_path, to_path)
        
        from_path=Rails.root.to_s+'/public/system/opt1_images/'+qid+'/medium/'+question.opt1_image_file_name
        to_path=Rails.root.to_s+'/public/system/questions_images/'+filename+'_medium.jpg'
        FileUtils.cp(from_path, to_path)
        
        from_path=Rails.root.to_s+'/public/system/opt1_images/'+qid+'/thumb/'+question.opt1_image_file_name
        to_path=Rails.root.to_s+'/public/system/questions_images/'+filename+'_thumb.jpg'
        FileUtils.cp(from_path, to_path)
  
        question.update_attribute(:opt1_image_file_name,filename+".jpg")
        
        filename=SecureRandom.hex(16)
        from_path=Rails.root.to_s+'/public/system/opt2_images/'+qid+'/original/'+question.opt2_image_file_name
        to_path=Rails.root.to_s+'/public/system/questions_images/'+filename+'_original.jpg'
        FileUtils.cp(from_path, to_path)
        
        from_path=Rails.root.to_s+'/public/system/opt2_images/'+qid+'/medium/'+question.opt2_image_file_name
        to_path=Rails.root.to_s+'/public/system/questions_images/'+filename+'_medium.jpg'
        FileUtils.cp(from_path, to_path)
        
        from_path=Rails.root.to_s+'/public/system/opt2_images/'+qid+'/thumb/'+question.opt2_image_file_name
        to_path=Rails.root.to_s+'/public/system/questions_images/'+filename+'_thumb.jpg'
        FileUtils.cp(from_path, to_path)
  
        question.update_attribute(:opt2_image_file_name,filename+".jpg")
        
        puts "moveds"+question.id.to_s
        rescue => e
          strnotice=strnotice+question.id.to_s+"-"
          next
        end
    end
      respond_to do |format|
        flash[:notice] = strnotice
        format.html { redirect_to wapproval_questions_url }
        format.json { head :no_content }
      end
  end
    
  def approve
    @question=Question.find(params[:id])
    @question.approve
    
    respond_to do |format|
      flash[:notice] = 'Question approved'
      format.html { redirect_to wapproval_questions_url }
      format.json { head :no_content }
    end
  end
  
   def wimages
   
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br />
  <div class="control-group">
  	<%= f.label 'Kategori:', :class=>"control-label" %>
  		<%= f.fields_for :category_questions do |builder| %>
 			<%= builder.collection_select(:category_id, @categories, :id, :name, :selected=>2) %>
  		<% end %>
  </div>
  <div class="field">
    <%= f.text_field :opt1, :class=>"span3", :placeholder=>"Seçenek 1..." %>
  	<%= f.file_field :opt1_image %>
  </div>
  <div class="field">
    <%= f.text_field :opt2,:class=>"span3" , :placeholder=>"Seçenek 2...…"%>
	<%= f.file_field :opt2_image %>
  </div>
  <div class="field">
    Point<br />
    <%= f.number_field :point, :class=>"span2" %>
  </div>
  <div class="field">
    Option1 count<br />
    <%= f.number_field :opt1_ac,:class=>"span2" %>
  </div>
  <div class="field">
    Option2 count<br />
    <%= f.number_field :opt2_ac,:class=>"span2" %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<%= link_to 'New Question', new_question_path , :class=>'btn btn-primary'%>
<br />
<h3>Questions</h3>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
<thead>
	
  <tr>
    <th>Functions</th>
    <th>ID </th>
    <th>Opt1</th>
    <th>count</th>
    <th>Opt2</th>
    <th>count</th>
    <th>created by</th>
    <th>created_at</th>
    <th>point</th>
  </tr>
</thead>
<tbody>
	
<% @questions.each do |question| %>
  <tr>
    <td><%= link_to "<i class='icon-share icon-black'></i>".html_safe, question, :title=> "Show" %>  
    	<%= link_to "<i class='icon-edit icon-black'></i>".html_safe, edit_question_path(question), :title=> "Edit" %>  
    	<%= link_to "<i class='icon-remove icon-black'></i>".html_safe, question,confirm: 'Are you sure musun?', method: :delete, :title=> "Delete" %> 
    	<%= link_to "<i class='icon-ok icon-black'></i>".html_safe, approve_question_path(question), method: :post, :title=>"Approve" if question.status=='wapproval' %>
    	</td>
    <td><%= question.id %></td>
    <td><%= question.opt1 %> </td>
    <td><%= question.opt1_ac %></td>
    <td><%= question.opt2 %> </td>
    <td><%= question.opt2_ac %> </td>
    <td><%= question.user_email %> </td>
    <td><%= question.created_at %> </td>
    <td><%= question.point %> </td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>
<div class="alert alert-info">
	<a class="close" data-dismiss="alert">×</a>
  * Soru girmeden önce <%= link_to 'tüm soru listesinden', questions_path %> arama yapınız, benzer/duplike kayıtlar olmasın :)<br />
  * Resimlerin genişliği ve uzunluğunun eşit veya yakın olmasına dikkat ediniz. <br />
  * Min resim boyutu 200x200 olmalı
</div>


<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/random.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span12">
    <div class="row">
      <div class="span6">
		  <%= @question.opt1 %>-<b><%= @question.opt1_ac %></b><br />
		  <%= image_tag @question.opt1_image.url(:medium) %>
      </div>
      <div class="span6">
		  <%= @question.opt2 %>-<b><%= @question.opt2_ac %></b><br />
		  <%= image_tag @question.opt2_image.url(:medium) %>
      </div>
    </div>
  </div>
</div>
<br />
<%= link_to 'Next Random', random_questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span12">
    <div class="row">
      <div class="span6">
		  <%= @question.opt1 %>-<b><%= @question.opt1_ac %></b><br />
		  <%= image_tag @question.opt1_image.url(:medium) %>
      </div>
      <div class="span6">
		  <%= @question.opt2 %>-<b><%= @question.opt2_ac %></b><br />
		  <%= image_tag @question.opt2_image.url(:medium) %>
      </div>
    </div>
  </div>
</div>
<br />

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %> |
<%= link_to 'New Question', new_question_path %>

app/views/questions/wimages.html.erb
<%= link_to 'New Question', new_question_path , :class=>'btn btn-primary'%>
<br />
<h3>Questions</h3>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
<thead>
	
  <tr>
    <th>Functions</th>
    <th>ID </th>
    <th>Opt1</th>
    <th>Opt1 image</th>
    <th>count</th>
    <th>Opt2</th>
    <th>Opt2 image</th>
    <th>count</th>
    <th>created by</th>
    <th>created_at</th>
    <th>point</th>
  </tr>
</thead>
<tbody>
	
<% @questions.each do |question| %>
  <tr>
    <td><%= link_to "<i class='icon-share icon-black'></i>".html_safe, question, :title=> "Show" %>  
    	<%= link_to "<i class='icon-edit icon-black'></i>".html_safe, edit_question_path(question), :title=> "Edit" %>  
    	<%= link_to "<i class='icon-remove icon-black'></i>".html_safe, question,confirm: 'Are you sure musun?', method: :delete, :title=> "Delete" %> 
    	<%= link_to "<i class='icon-ok icon-black'></i>".html_safe, approve_question_path(question), method: :post, :title=>"Approve" if question.status=='wapproval' %>
    	</td>
    <td><%= question.id %></td>
    <td><%= question.opt1 %> </td>
    <td><%= image_tag question.opt1_image.url(:thumb) %> </td>
    <td><%= question.opt1_ac %></td>
    <td><%= question.opt2 %> </td>
    <td><%= image_tag question.opt2_image.url(:thumb) %> </td>
    <td><%= question.opt2_ac %> </td>
    <td><%= question.user_email %> </td>
    <td><%= question.created_at %> </td>
    <td><%= question.point %> </td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Question', new_question_path %>