config/routes.rb
Sence::Application.routes.draw do
  
  resources :category_questions

  resources :categories

  resources :profiles

  resources :answers do
    collection do
      get 'history' => 'answers#history'
      get 'summary' => 'answers#summary'
    end
  end

  resources :questions do 
    collection do
      get 'mine' => 'questions#index'
      get 'nopicture' => 'questions#index'
      get 'random'
      get 'wapproval' => 'questions#index'
      get 'wimages'
    end
    member do
      post :approve
      get 'stats'
    end
  end
  
  devise_for :users,:controllers => {:sessions => "sessions",:registrations => "registrations"}
  
  resources :users do
    resources :questions
    resources :answers
    resources :profiles
  end

  match 'logout' => 'devise/session#destroy'
  match 'myrank' => 'profiles#myrank'
  match 'most' => 'statistics#most_answered'
  match 'gap' => 'statistics#gap'
  match 'aomq' => 'statistics#aomq'
  

   root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @question_count= Question.count
    @answer_count= Answer.count
    @user_count= User.count
    @nopicture_count=Question.nopicture.count
    @wapproval_count=Question.all_wapproval.count
    
    sql="select count(*) cnt, u.email,q.user_id from users u, questions q where u.id=q.user_id group by q.user_id"
    @user_questions = Question.find_by_sql([sql])
  end
end

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>sence?dashboard</h1>
  <p>
  	
    <%= link_to "<i class='icon-question-sign icon-white'></i> #{t('New')}".html_safe, new_question_path, :class=>'btn btn-large btn-primary' %>
    <%= link_to "<i class='icon-random icon-white'></i> #{t('Random')}".html_safe, random_questions_path, :class=>'btn btn-large btn-success' %>
    <%= link_to "<i class='icon-star icon-white'></i> #{t('Mine')}".html_safe, mine_questions_path, :class=>'btn btn-large btn-warning' %>
    <%= link_to "<i class='icon-picture icon-white'></i> #{t("No Picture ("+@nopicture_count.to_s+")")}".html_safe, nopicture_questions_path, :class=>'btn btn-large btn-inverse' %>
    <%= link_to "<i class='icon-ok icon-white'></i> #{t("Waiting Approvals ("+@wapproval_count.to_s+")")}".html_safe, wapproval_questions_path, :class=>'btn btn-large btn-info' %>
  </p>

  <b><%= @question_count %></b> questions,
  <b><%= @answer_count %></b> answers and 
  <b><%= @user_count %></b> users
</div>
 <table class="table table-condensed">
  <tr>
    <th>User</th>
    <th>Question Count</th>
  </tr>
  	<% @user_questions.each do |user_question| %>
	  <tr>
	    <td><%= link_to user_question.email, user_questions_path(user_question.user_id) %></td>
	    <td><%= link_to user_question.cnt, user_questions_path(user_question.user_id) %></td>
	  </tr>
	<% end %>
</table>