config/routes.rb
Sence::Application.routes.draw do
  
  resources :category_questions

  resources :categories

  resources :profiles

  resources :answers do
    collection do
      get 'history' => 'answers#history'
      get 'summary' => 'answers#summary'
    end
  end

  resources :questions do 
    collection do
      get 'mine' => 'questions#index'
      get 'nopicture' => 'questions#index'
      get 'random'
      get 'wapproval' => 'questions#index'
      get 'wimages'
    end
    member do
      post :approve
      get 'stats'
    end
  end
  
  devise_for :users,:controllers => {:sessions => "sessions",:registrations => "registrations"}
  
  resources :users do
    resources :questions
    resources :answers
    resources :profiles
  end

  match 'logout' => 'devise/session#destroy'
  match 'myrank' => 'profiles#myrank'
  match 'most' => 'statistics#most_answered'
  match 'gap' => 'statistics#gap'
  match 'aomq' => 'statistics#aomq'
  

   root :to => 'home#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  
  validates_presence_of :user
  validates_presence_of :question
  validates_uniqueness_of :question_id, :scope => [:user_id] 
  
  default_scope :order => 'created_at desc'

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  load_and_authorize_resource
  skip_authorize_resource :only => :history
  def index
    if params[:user_id]
      @user=User.find(params[:user_id])
      @answers = @user.answers  
    else
      @answers = Answer.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end
  
  def summary
    sql="select u.id user_id,u.email,(select count(*) from answers where user_id=u.id) answer_count,
     (select max(created_at) from answers where user_id=u.id) last_answer_date from users u"
    
    #puts sql
    @answers = Answer.find_by_sql(sql)

    respond_to do |format|
      format.html
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])
    @user = User.find(current_user)
    @answer.user_id=@user.id
    question = Question.find(@answer.question_id)
    profile=@user.profile
    
    
    opt1_count=(question.opt1_ac).to_i
    opt2_count=(question.opt2_ac).to_i
    total_answers=opt1_count+opt2_count
    
    if @answer.opt==1
      question.opt1_ac= opt1_count+ 1
    else
      question.opt2_ac= opt2_count+ 1
    end
    
    message=""
    points_gained=question.point
    
    if total_answers==0
      message="ilk cevap"
      points_gained=10
    elsif total_answers==99
      message="100. cevap"
      points_gained=100
    elsif total_answers==99
      message="1000. cevap"
      points_gained=1000
    elsif opt1_count==opt2_count and opt1_count!=0 and opt2_count!=0
      message="dengeyi bozdun"
      points_gained=50
    end
    
    profile.points=(@user.profile.points).to_i+points_gained.to_i
    
    respond_to do |format|
      ActiveRecord::Base.transaction do
        @answer.save!
        question.save!
        profile.save!
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        #format.json { render json: [@question.to_json(:only=> [:opt1_ac,:opt2_ac]),profile.to_json(:only=>:points)], status: :created, location: @answer }
        
        format.json { render json:{:opt1_ac=>question.opt1_ac,:opt2_ac=>question.opt2_ac,:points_gained=>points_gained,:message=>message,:points=>profile.points}, status: :created, location: @answer }
      end      
    end
    
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved
      format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
   end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
  
  def history
    @user = User.find(current_user)
    
    sql="select q.opt1,q.opt2,q.point,a.opt, a.created_at,q.opt1_ac, q.opt2_ac from questions q, answers a 
         where q.id=a.question_id and a.user_id=? order by a.created_at desc limit 50"
         
    @answers = Answer.find_by_sql([sql,@user.id])
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @answers }
      end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :opt %><br />
    <%= f.number_field :opt %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table class="table table-striped table-condensed">
  <tr>
    <th>Question</th>
    <th>Opt</th>
    <th>User</th>
    <th>Created At</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.question_id %></td>
    <td><%= answer.opt %></td>
    <td><%= answer.user_id %></td>
    <td><%= answer.created_at %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @answer.question_id %>
</p>

<p>
  <b>Opt:</b>
  <%= @answer.opt %>
</p>

<p>
  <b>User:</b>
  <%= @answer.user_id %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/answers/summary.html.erb
<h1>Listing answers</h1>

<table class="table">
  <tr>
    <th></th>
    <th>User</th>
    <th>Answer Count</th>
    <th>Last Answer Date</th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= link_to "<i class='icon-share icon-black'></i>".html_safe, user_answers_path(answer.user_id), :title=> "Show" %></td>
    <td><%= answer.email %></td>
    <td><%= answer.answer_count %></td>
    <td><%= answer.last_answer_date %></td>
  </tr>
<% end %>
</table>

<br />