config/routes.rb
Sence::Application.routes.draw do
  
  resources :category_questions

  resources :categories

  resources :profiles

  resources :answers do
    collection do
      get 'history' => 'answers#history'
      get 'summary' => 'answers#summary'
    end
  end

  resources :questions do 
    collection do
      get 'mine' => 'questions#index'
      get 'nopicture' => 'questions#index'
      get 'random'
      get 'wapproval' => 'questions#index'
      get 'wimages'
    end
    member do
      post :approve
      get 'stats'
    end
  end
  
  devise_for :users,:controllers => {:sessions => "sessions",:registrations => "registrations"}
  
  resources :users do
    resources :questions
    resources :answers
    resources :profiles
  end

  match 'logout' => 'devise/session#destroy'
  match 'myrank' => 'profiles#myrank'
  match 'most' => 'statistics#most_answered'
  match 'gap' => 'statistics#gap'
  match 'aomq' => 'statistics#aomq'
  

   root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>sence?</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="<%= root_url%>">
              sence?
            </a>
        	<%- if !current_user.nil? %>
        	
             <ul class="nav">
				<li><%=link_to "Dashboard", root_url %></li>
				<li><%=link_to "Users", users_path %></li>
             	<li class="dropdown"> 
					<a href="#"
                      class="dropdown-toggle"
                      data-toggle="dropdown">
                      Questions
                      <b class="caret"></b>
                	</a>
                	<ul class="dropdown-menu">
						<li><%=link_to "All Questions", questions_path %></li>
						<li><%=link_to "My Questions", mine_questions_path %></li>
						<li><%=link_to "Waiting Approvals", wapproval_questions_path %></li>
                	</ul>
				</li>
				<li><%=link_to "Answers", summary_answers_path %></li>
				<li><%=link_to "Categories", categories_path %></li>
			</ul> 
			<ul class="nav pull-right">
               <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul> 
			<%- end -%>
        </div>
      </div>
	</div>
	
	<div class="container">
	    <%- if !notice.nil? or !alert.nil? -%>
		    <div class="alert alert-block">
			 	<a class="close" data-dismiss="alert">×</a>
				 <%= notice %>
				 <%= alert %>
			</div>
		<%- end -%>
		
		<%= yield %>
	<div>

</div>	
<!-- <%= debug(params) if Rails.env.development? %> -->
</body>
</html>
</html>